from django.urls import path
from . import views
from .views import posts_with_user, get_likes_list, toggle_like, comments_view, record_video_view, save_view_log, watch_matrix # ← mypage は削除

urlpatterns = [
    path("tests/create/", views.create_test),
    path("posts/", views.posts_list_create, name="posts_list_create"),
    path('posts_with_user/', posts_with_user, name='posts_with_user'),
    path('posts/<int:pk>/update/', views.update_post, name='update_post'),
    path("posts/<uuid:pk>/delete/", views.delete_post, name="delete_post"),
    path('posts/<uuid:pk>/', views.post_detail, name='post_detail'),
    path("posts/<uuid:pk>/likes/", views.get_likes_list, name="get_likes_list"),
    path("posts/<uuid:pk>/like/", views.toggle_like, name="toggle_like"),
    path("posts/<uuid:pk>/comments/", views.comments_view, name="comments_view"),
    path("hashtags/search/", views.search_hashtags, name="search_hashtags"),
    path("videos/view_logs/", views.video_view_logs),
    path("videos/save_log/", save_view_log, name="save_view_log"),
     path("videos/add_view/", views.add_video_view),
     path("videos/record_view/", views.record_video_view, name="record_video_view"),
     path("videos/<str:video_id>/", views.video_detail, name="video_detail"),
     path("videos/<str:video_id>/test/", views.video_test_detail),
     path("videos/<str:video_id>/test/submit/", views.submit_test),
     path("videos/<str:video_id>/survey/submit/", views.submit_survey),
     path("videos/<str:video_id>/survey/", views.get_video_survey),
     path("videos/", views.video_list, name="video_list"),
     path("videos/create/", views.create_video, name="create_video"),
     path("videos/<str:video_id>/update/", views.update_video, name="update_video"), # ← 追加
     path("treasures/", views.treasure_list, name="treasure_list"),
     path("treasure_posts/", views.treasure_post_list, name="treasure_post_list"),
     path("treasure_posts/<uuid:pk>/", views.treasure_post_detail, name="treasure_post_detail"),
     path("treasure_posts/<uuid:pk>/like/", views.toggle_treasure_like, name="toggle_treasure_like"),
     path("treasure_posts/<uuid:pk>/comments/", views.treasure_comments_view, name="treasure_comments_view"),
     path("treasure_posts/titles/", views.treasure_titles_view, name="treasure_titles"),
     path("treasure_posts/category_counts/", views.treasure_category_counts, name="treasure_category_counts"),
     path("notices/", views.notices_list_create),
    path("notices/<uuid:pk>/", views.notice_detail),
    path("fetch-ogp/", views.fetch_ogp),
     path("analytics/watch_matrix/", watch_matrix),
    path("admin/home/content/", views.get_home_content),
    path("admin/posts/<uuid:pk>/toggle_featured/", views.toggle_featured_post),
    path("admin/videos/<str:pk>/toggle_featured/", views.toggle_featured_video), # ← 追加
    path("admin/videos/<str:pk>/toggle_short/", views.toggle_short_video),
    path("office_news/", views.office_news_list_create),
    path("office_news/<uuid:pk>/", views.office_news_detail),
    path("admin/posts/list/", views.admin_post_list),
    path("task_buttons/", views.task_button_list_create),
    path("task_buttons/<uuid:pk>/", views.task_button_detail),
    path("admin/videos/list/", views.admin_video_list),
    path("log/interaction/", views.log_interaction),
    path("admin/interaction-logs/", views.admin_interaction_logs),
]