# Generated by Django 5.2.7 on 2025-12-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_surveyquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(default='choice', max_length=50),
        ),
    ]
