# Generated by Django 5.2.7 on 2025-12-16 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_surveyquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='posts.usertestresult')),
            ],
        ),
    ]
