# Generated by Django 5.2.7 on 2025-12-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_hashtags_post_mentions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.AddField(
            model_name='notice',
            name='external_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_short',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
