# Generated by Django 5.2.7 on 2025-12-23 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_delete_badge_notice_external_url_post_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('external_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'office_news',
                'ordering': ['-created_at'],
            },
        ),
    ]
