# Generated by Django 5.2.7 on 2025-12-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_officenews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officenews',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='officenews',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='office_news/'),
        ),
    ]
