# Generated by Django 5.2.7 on 2025-12-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_officenews_thumbnail_url_officenews_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
