# Generated by Django 5.2.7 on 2025-12-25 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_video_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=50)),
                ('color', models.CharField(default='text-gray-800', max_length=50)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=50)),
                ('parent_category', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
