# Generated by Django 5.2.7 on 2025-12-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_taskbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurepost',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treasurepost',
            name='anxiety_needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treasurepost',
            name='appeal_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treasurepost',
            name='device_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treasurepost',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
