# Generated by Django 5.2.7 on 2025-12-26 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_treasurepost_age_treasurepost_anxiety_needs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interaction_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
