# Generated by Django 5.2.7 on 2025-12-26 04:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_userinteractionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPopupSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popup_setting', to='posts.notice')),
            ],
        ),
    ]
