# Generated by Django 5.2.7 on 2025-12-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_loginpopupsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_login_popup',
            field=models.BooleanField(default=False),
        ),
    ]
