# Generated by Django 5.2.7 on 2025-12-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_notice_is_login_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officenews',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
