# Generated by Django 5.2.7 on 2026-01-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_officenews_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='treasurecomment',
            name='user_uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
