# Generated by Django 5.2.7 on 2026-01-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_comment_user_uid_treasurecomment_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='treasurecomment',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
