# Generated by Django 5.2.7 on 2026-01-08 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='treasurecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.treasurecomment'),
        ),
        migrations.AddField(
            model_name='treasurecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
