# Generated by Django 5.2.7 on 2026-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_treasurepost_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
