# Generated by Django 5.2.7 on 2026-01-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_question_description_surveyquestion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='summary_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
