# Generated by Django 5.2.7 on 2026-01-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_notice_summary_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='parent_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
