# Generated by Django 5.2.7 on 2026-02-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_video_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
