# Generated by Django 5.2.7 on 2026-02-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_post_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurepost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
