# Generated by Django 5.2.7 on 2026-02-04 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_treasurepost_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasurecomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_treasure_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
