# Generated by Django 5.2.7 on 2025-12-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_badge_remove_user_badges_user_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expMax',
            field=models.IntegerField(default=500),
        ),
    ]
