# Generated by Django 5.2.7 on 2025-12-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_popup_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
