# Generated by Django 5.2.7 on 2025-12-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_last_seen_popup_id_user_login_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'いいね'), ('COMMENT', 'コメント'), ('MENTION', 'メンション'), ('BADGE', 'バッジ付与'), ('POINT', 'ポイント変動'), ('NEWS', 'お知らせ')], max_length=20),
        ),
    ]
