# Generated by Django 5.2.7 on 2026-01-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'いいね'), ('COMMENT', 'コメント'), ('REPLY', '返信'), ('MENTION', 'メンション'), ('BADGE', 'バッジ付与'), ('POINT', 'ポイント変動'), ('NEWS', 'お知らせ')], max_length=20),
        ),
    ]
