# Generated by Django 5.2.7 on 2026-01-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
