# Generated by Django 5.2.7 on 2026-01-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_terms_agreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_treasure_post',
            field=models.BooleanField(default=False),
        ),
    ]
