# Generated by Django 5.2.7 on 2025-12-26 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exp_reward', models.IntegerField(default=1)),
                ('mission_type', models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY')], max_length=10)),
                ('team', models.CharField(choices=[('shop', 'Pixel-Shop'), ('event', 'Pixel-Event')], max_length=10)),
                ('action_type', models.CharField(max_length=50)),
                ('action_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('target_count', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('is_shop_wide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
